# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import MyResources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(610, 740)
        MainWindow.setStyleSheet(u"background-color: rgb(221, 233, 255);")
        self.btn7 = QPushButton(MainWindow)
        self.btn7.setObjectName(u"btn7")
        self.btn7.setGeometry(QRect(10, 140, 140, 140))
        icon = QIcon()
        icon.addFile(u"Images/7.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn7.setIcon(icon)
        self.btn7.setIconSize(QSize(140, 140))
        self.btn4 = QPushButton(MainWindow)
        self.btn4.setObjectName(u"btn4")
        self.btn4.setGeometry(QRect(10, 290, 140, 140))
        icon1 = QIcon()
        icon1.addFile(u"Images/4.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn4.setIcon(icon1)
        self.btn4.setIconSize(QSize(140, 140))
        self.pushButton_3 = QPushButton(MainWindow)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 440, 140, 140))
        self.pushButton_4 = QPushButton(MainWindow)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 590, 140, 140))
        self.btn1 = QPushButton(MainWindow)
        self.btn1.setObjectName(u"btn1")
        self.btn1.setGeometry(QRect(10, 440, 140, 140))
        icon2 = QIcon()
        icon2.addFile(u"Images/1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn1.setIcon(icon2)
        self.btn1.setIconSize(QSize(140, 140))
        self.btn0 = QPushButton(MainWindow)
        self.btn0.setObjectName(u"btn0")
        self.btn0.setGeometry(QRect(10, 590, 140, 140))
        icon3 = QIcon()
        icon3.addFile(u"Images/0.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn0.setIcon(icon3)
        self.btn0.setIconSize(QSize(140, 140))
        self.btn8 = QPushButton(MainWindow)
        self.btn8.setObjectName(u"btn8")
        self.btn8.setGeometry(QRect(160, 140, 140, 140))
        icon4 = QIcon()
        icon4.addFile(u"Images/8.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn8.setIcon(icon4)
        self.btn8.setIconSize(QSize(140, 140))
        self.btn2 = QPushButton(MainWindow)
        self.btn2.setObjectName(u"btn2")
        self.btn2.setGeometry(QRect(160, 440, 140, 140))
        icon5 = QIcon()
        icon5.addFile(u"Images/2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn2.setIcon(icon5)
        self.btn2.setIconSize(QSize(140, 140))
        self.btndot = QPushButton(MainWindow)
        self.btndot.setObjectName(u"btndot")
        self.btndot.setGeometry(QRect(160, 590, 140, 140))
        icon6 = QIcon()
        icon6.addFile(u"Images/dot.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btndot.setIcon(icon6)
        self.btndot.setIconSize(QSize(140, 140))
        self.btn5 = QPushButton(MainWindow)
        self.btn5.setObjectName(u"btn5")
        self.btn5.setGeometry(QRect(160, 290, 140, 140))
        font = QFont()
        font.setPointSize(48)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet(u"")
        icon7 = QIcon()
        icon7.addFile(u"Images/5.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn5.setIcon(icon7)
        self.btn5.setIconSize(QSize(140, 140))
        self.btndevide = QPushButton(MainWindow)
        self.btndevide.setObjectName(u"btndevide")
        self.btndevide.setGeometry(QRect(460, 290, 140, 140))
        icon8 = QIcon()
        icon8.addFile(u"Images/dev.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btndevide.setIcon(icon8)
        self.btndevide.setIconSize(QSize(140, 140))
        self.pushButton_12 = QPushButton(MainWindow)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(310, 440, 140, 140))
        self.btnminus = QPushButton(MainWindow)
        self.btnminus.setObjectName(u"btnminus")
        self.btnminus.setGeometry(QRect(460, 590, 140, 140))
        icon9 = QIcon()
        icon9.addFile(u"Images/min.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnminus.setIcon(icon9)
        self.btnminus.setIconSize(QSize(140, 140))
        self.pushButton_14 = QPushButton(MainWindow)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(310, 590, 140, 140))
        self.btnplus = QPushButton(MainWindow)
        self.btnplus.setObjectName(u"btnplus")
        self.btnplus.setGeometry(QRect(460, 440, 140, 140))
        icon10 = QIcon()
        icon10.addFile(u"Images/plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnplus.setIcon(icon10)
        self.btnplus.setIconSize(QSize(140, 140))
        self.btnmulti = QPushButton(MainWindow)
        self.btnmulti.setObjectName(u"btnmulti")
        self.btnmulti.setGeometry(QRect(460, 140, 140, 140))
        icon11 = QIcon()
        icon11.addFile(u"Images/mul.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnmulti.setIcon(icon11)
        self.btnmulti.setIconSize(QSize(140, 140))
        self.btn9 = QPushButton(MainWindow)
        self.btn9.setObjectName(u"btn9")
        self.btn9.setGeometry(QRect(310, 140, 140, 140))
        icon12 = QIcon()
        icon12.addFile(u"Images/9.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn9.setIcon(icon12)
        self.btn9.setIconSize(QSize(140, 140))
        self.btn6 = QPushButton(MainWindow)
        self.btn6.setObjectName(u"btn6")
        self.btn6.setGeometry(QRect(310, 290, 140, 140))
        icon13 = QIcon()
        icon13.addFile(u"Images/6.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn6.setIcon(icon13)
        self.btn6.setIconSize(QSize(140, 140))
        self.btn3 = QPushButton(MainWindow)
        self.btn3.setObjectName(u"btn3")
        self.btn3.setGeometry(QRect(310, 440, 140, 140))
        icon14 = QIcon()
        icon14.addFile(u"Images/3.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn3.setIcon(icon14)
        self.btn3.setIconSize(QSize(140, 140))
        self.btnequal = QPushButton(MainWindow)
        self.btnequal.setObjectName(u"btnequal")
        self.btnequal.setGeometry(QRect(310, 590, 140, 140))
        icon15 = QIcon()
        icon15.addFile(u"Images/eq.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnequal.setIcon(icon15)
        self.btnequal.setIconSize(QSize(140, 140))
        self.lbl = QLabel(MainWindow)
        self.lbl.setObjectName(u"lbl")
        self.lbl.setGeometry(QRect(10, 10, 591, 121))
        font1 = QFont()
        font1.setFamily(u"Digital-7")
        font1.setPointSize(72)
        self.lbl.setFont(font1)
        self.lbl.setStyleSheet(u"background-color: rgb(55, 255, 242);")
        self.lbl.setFrameShape(QFrame.Box)
        self.lbl.setFrameShadow(QFrame.Plain)
        self.lbl.setLineWidth(4)
        self.btn5.raise_()
        self.btn7.raise_()
        self.btn4.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.btn1.raise_()
        self.btn0.raise_()
        self.btn8.raise_()
        self.btn2.raise_()
        self.btndot.raise_()
        self.btndevide.raise_()
        self.pushButton_12.raise_()
        self.btnminus.raise_()
        self.pushButton_14.raise_()
        self.btnplus.raise_()
        self.btnmulti.raise_()
        self.btn9.raise_()
        self.btn6.raise_()
        self.btn3.raise_()
        self.btnequal.raise_()
        self.lbl.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Form", None))
        self.btn7.setText("")
        self.btn4.setText("")
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.btn1.setText("")
        self.btn0.setText("")
        self.btn8.setText("")
        self.btn2.setText("")
        self.btndot.setText("")
        self.btn5.setText("")
        self.btndevide.setText("")
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.btnminus.setText("")
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.btnplus.setText("")
        self.btnmulti.setText("")
        self.btn9.setText("")
        self.btn6.setText("")
        self.btn3.setText("")
        self.btnequal.setText("")
        self.lbl.setText("")
    # retranslateUi

